name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - environment.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          docker build -t $IMAGE -f Dockerfile .
          echo "Built image $IMAGE"

      - name: Push the Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          docker push $IMAGE
